/*************************************************************
*    Project Euler's Problem 2
*    This solution by Dylan Wilson
*    
*    Each new term in the Fibonacci sequence is generated by adding the previous
*    two terms. Starting with 1 and 2 consider the terms in the Fibonacci
*    sequence whose values do not exceed four million. Find the sum of the
*    even-valued terms.
*    ---------------------------------------------------------------------------
*    Another that I solved with programming instead of math. At least, from a
*    programming perspective, it's not to bad.
**************************************************************/

#include <stdio.h>

int KEY = 4000000;

int main()
{
    int fib1 = 1; //These are the starting values for the problem
    int fib2 = 2;

    int fib3; //This will contain the answer for the next number in the sequence.

    int total = 2; //This starts at 2 due to never checking fib2 if it's even.
    int counter = 1; //When this hits 3 it's an even number.

    do //Not using recursion because it's horribly inefficient for something like this.
    {
        fib3 = fib1 + fib2;
        fib1 = fib2;
        fib2 = fib3;

        if(counter == 3) //Avoiding mod because it's slower, would be obvious at higher values.
        {   
            total += fib3;
	    counter = 1;
        }
	else
	{
	    counter++;
	}

    }while(fib3<KEY);

    printf("%d",total);

    return 0;
}